# Generated by Django 3.2.16 on 2026-01-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options'),
        ('blog', '0004_comment'),
    ]

    operations = [
    ]
